[project]
name = "mushakkil"
version = "0.0.1"
description = "Arabic diacritization system"
readme = "README.md"
authors = [
    { name = "Faris Al-Amri" },
    { name = "Khalid Alanazi" },
    { name = "Mujahid Alkhuzayyim"},
    { name = "Rama Alaqeeli"},
    { name = "Renad Filfilan"}
]
requires-python = ">=3.13,<3.14"
dependencies = [
    "datasets>=5.0.1",
    "kagglehub>=1.0.2",
    "keras>=3.12.4",
    "pandas>=2.3.3",
    "pyarabic>=0.6.15",
    "regex>=2026.7.19",
    "tensorflow>=2.21.0",
    "transformers>=5.15.1",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.1",
]
